<?php

function kills_menu() {
    $items['statistics'] = array(
        'page callback' => 'stats_view',
        'access callback' => TRUE,
    );
    $items['get_deaths'] = array(
        'page callback' => '_service_get_deaths',
        'access callback' => TRUE,
    );
    $items['get_injuries'] = array(
        'page callback' => '_service_get_injuries',
        'access callback' => TRUE,
    );
    return $items;
}
function _service_get_injuries(){
    $query = db_select("node", "n");
    $query->join("field_data_field_incident_date", "id", "n.nid=id.entity_id");
    $query->join("field_data_field_no_of_injured", "d", "n.nid=d.entity_id");
    $query->fields("id", array("field_incident_date_value"));
    $query->fields("d", array("field_no_of_injured_value"));
    $result = $query->execute()->fetchAll();
    $array = array_fill(0, 11, 0);
   // print_r($array);exit;
    
    foreach ($result as $incident){
     //   echo date("Y",$incident-> field_incident_date_value);
        if(date("Y",$incident-> field_incident_date_value) == "2002"){
            $array[0] += $incident-> field_no_of_injured_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2003"){
            $array[1] += $incident-> field_no_of_injured_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2004"){
            $array[2] += $incident-> field_no_of_injured_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2005"){
            $array[3] += $incident-> field_no_of_injured_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2006"){
            $array[4] += $incident-> field_no_of_injured_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2007"){
            $array[5] += $incident-> field_no_of_injured_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2008"){
            $array[6] += $incident-> field_no_of_injured_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2009"){
            $array[7] += $incident-> field_no_of_injured_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2010"){
            $array[8] += $incident-> field_no_of_injured_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2011"){
            $array[9] += $incident-> field_no_of_injured_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2012"){
            //echo "adads";exit;
            $array[10] += $incident-> field_no_of_injured_value;
        }
    }
    echo drupal_json_encode($array);
}
function _service_get_deaths(){
    $query = db_select("node", "n");
    $query->join("field_data_field_incident_date", "id", "n.nid=id.entity_id");
    $query->join("field_revision_field_no_of_deaths", "d", "n.nid=d.entity_id");
    $query->fields("id", array("field_incident_date_value"));
    $query->fields("d", array("field_no_of_deaths_value"));
    $result = $query->execute()->fetchAll();
    $array = array_fill(0, 11, 0);
   // print_r($array);exit;
    
    foreach ($result as $incident){
     //   echo date("Y",$incident-> field_incident_date_value);
        if(date("Y",$incident-> field_incident_date_value) == "2002"){
            $array[0] += $incident-> field_no_of_deaths_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2003"){
            $array[1] += $incident-> field_no_of_deaths_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2004"){
            $array[2] += $incident-> field_no_of_deaths_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2005"){
            $array[3] += $incident-> field_no_of_deaths_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2006"){
            $array[4] += $incident-> field_no_of_deaths_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2007"){
            $array[5] += $incident-> field_no_of_deaths_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2008"){
            $array[6] += $incident-> field_no_of_deaths_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2009"){
            $array[7] += $incident-> field_no_of_deaths_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2010"){
            $array[8] += $incident-> field_no_of_deaths_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2011"){
            $array[9] += $incident-> field_no_of_deaths_value;
        }
        if(date("Y",$incident-> field_incident_date_value) == "2012"){
            //echo "adads";exit;
            $array[10] += $incident-> field_no_of_deaths_value;
        }
    }
    echo drupal_json_encode($array);
}
function stats_view() {
   $path = drupal_get_path('module', 'kills');
   drupal_add_js($path . '/js/ajax.js', array('weight' => 1));
   drupal_add_js($path . '/js/highcharts.js', array('weight' => 1));
   drupal_add_js($path . '/kills.js', array('weight' => 1));
   
   $page = "<h2><center>TOTAL NO. OF DEATHS RECORDED</CENTER></h2>";
   $page .= calculate_deaths_in_all_provices();
   $page .= "<BR/><BR/><h2><center>TOTAL NO. OF INJURIES RECORDED</CENTER></h2>";
   $page.=calculate_injuries_in_all_provices();
   $page .= '<br/><br/><div id="container" style="min-width: 400px; height: 400px; margin: 0 auto"></div>';
    return $page;
}
function calculate_injuries_in_all_provices() {
    $header = array(
        array('data' => t('Punjab')),
        array('data' => t('Sindh')),
        array('data' => 'Balochistan'),
        array('data' => 'KPK'),
        array('data' => 'Baltistan/FATA'),
    );
    //$header = array('No. of deads in Punjab', 'No. of deads in Sindh', 'No. of deads in Balochistan', 'No. of deads in KPK', 'No. of deads in Gilgit Baltistan/FATA');
    $query = db_select("node", "n");
    $query->join("field_data_field_incident_province", "p", "n.nid=p.entity_id");
    $query->join("field_data_field_no_of_injured", "d", "n.nid=d.entity_id");
    $query->fields("p", array("field_incident_province_value"));
    $query->fields("d", array("field_no_of_injured_value"));
    $result = $query->execute()->fetchAll();
    $punjab_deaths = array();
    $sindh_deaths = array();
    $bal_deaths = array();
    $kpk_deaths = array();
    $fata_deaths = array();
    foreach ($result as $death) {
        if ($death->field_incident_province_value == "Punjab") {
            array_push($punjab_deaths, $death->field_no_of_injured_value);
        } else if ($death->field_incident_province_value == "Sindh") {
            array_push($sindh_deaths, $death->field_no_of_injured_value);
        } else if ($death->field_incident_province_value == "Balochistan") {
            array_push($bal_deaths, $death->field_no_of_injured_value);
        } else if ($death->field_incident_province_value == "KPK") {
            array_push($kpk_deaths, $death->field_no_of_injured_value);
        } else if ($death->field_incident_province_value == "Gilgit" || $death->field_incident_province_value == "FATA") {
            array_push($fata_deaths, $death->field_no_of_injured_value);
        }
    }
    $sum [] = array(
        array_sum($punjab_deaths),
        array_sum($sindh_deaths),
        array_sum($bal_deaths),
        array_sum($kpk_deaths),
        array_sum($fata_deaths),
    );
    $table = theme('table', array(
        'header' => $header,
        'rows' => $sum,
        'empty' => 'No Incident reported yet ...',
        )
    );    

    return $table;
}
function calculate_deaths_in_all_provices() {
    $header = array(
        array('data' => t('Punjab')),
        array('data' => t('Sindh')),
        array('data' => 'Balochistan'),
        array('data' => 'KPK'),
        array('data' => 'Baltistan/FATA'),
    );
    //$header = array('No. of deads in Punjab', 'No. of deads in Sindh', 'No. of deads in Balochistan', 'No. of deads in KPK', 'No. of deads in Gilgit Baltistan/FATA');
    $query = db_select("node", "n");
    $query->join("field_data_field_incident_province", "p", "n.nid=p.entity_id");
    $query->join("field_data_field_no_of_deaths", "d", "n.nid=d.entity_id");
    $query->fields("p", array("field_incident_province_value"));
    $query->fields("d", array("field_no_of_deaths_value"));
    $result = $query->execute()->fetchAll();
    $punjab_deaths = array();
    $sindh_deaths = array();
    $bal_deaths = array();
    $kpk_deaths = array();
    $fata_deaths = array();
    foreach ($result as $death) {
        if ($death->field_incident_province_value == "Punjab") {
            array_push($punjab_deaths, $death->field_no_of_deaths_value);
        } else if ($death->field_incident_province_value == "Sindh") {
            array_push($sindh_deaths, $death->field_no_of_deaths_value);
        } else if ($death->field_incident_province_value == "Balochistan") {
            array_push($bal_deaths, $death->field_no_of_deaths_value);
        } else if ($death->field_incident_province_value == "KPK") {
            array_push($kpk_deaths, $death->field_no_of_deaths_value);
        } else if ($death->field_incident_province_value == "Gilgit" || $death->field_incident_province_value == "FATA") {
            array_push($fata_deaths, $death->field_no_of_deaths_value);
        }
    }
    $sum [] = array(
        array_sum($punjab_deaths),
        array_sum($sindh_deaths),
        array_sum($bal_deaths),
        array_sum($kpk_deaths),
        array_sum($fata_deaths),
    );
    $table = theme('table', array(
        'header' => $header,
        'rows' => $sum,
        'empty' => 'No Incident reported yet ...',
        )
    );    

    return $table;
}